import type { Addon, Product } from './types';

export const products: Product[] = [
  {
    id: 'gs-city-01',
    category: 'city',
    name: 'Volt Street S',
    kicker: 'Городской электроскутер',
    price: 86400,
    oldPrice: 92900,
    monthly: 7080,
    range: 65,
    speed: 45,
    battery: '20 А·ч',
    payload: 150,
    stockLabel: 'Наличие уточняется',
    stockTone: 'available',
    color: '#5b8cff',
    colorSoft: '#dbe7ff',
    image: '/products/city-dark.webp',
    imageAlt: 'Белый городской электроскутер, вид в три четверти',
    visualVariant: 'step',
    description: 'Манёвренная городская модель для длинной смены и ежедневных маршрутов по побережью.',
    features: ['Съёмный аккумулятор', 'Гидравлические тормоза', 'Защита от брызг'],
    useCase: 'Ежедневные поездки по городу',
    weight: 58,
    chargeTime: '6–8 часов',
    dimensions: '176 × 70 × 112 см',
    wheelLayout: '2 колеса',
  },
  {
    id: 'gs-cargo-01',
    category: 'cargo',
    name: 'Volt Cargo X',
    kicker: 'Усиленная грузовая рама',
    price: 119900,
    monthly: 9830,
    range: 80,
    speed: 40,
    battery: '32 А·ч',
    payload: 220,
    stockLabel: 'Наличие уточняется',
    stockTone: 'limited',
    color: '#765cff',
    colorSoft: '#e5dfff',
    image: '/products/hero-cargo-orange.webp',
    imageAlt: 'Красный трёхколёсный грузовой электроскутер с корзиной и пассажирским сиденьем',
    visualVariant: 'cargo',
    description: 'Усиленная конструкция для двух термокоробов и маршрутов с высокой загрузкой.',
    features: ['Задняя грузовая платформа', 'Двойная подножка', 'Усиленная подвеска'],
    useCase: 'Работа, доставка и перевозка груза',
    weight: 104,
    chargeTime: '7–9 часов',
    dimensions: '196 × 82 × 118 см',
    wheelLayout: '3 колеса',
  },
  {
    id: 'gs-compact-01',
    category: 'compact',
    name: 'Zip Mini 14',
    kicker: 'Компактный формат',
    price: 74900,
    monthly: 6140,
    range: 48,
    speed: 35,
    battery: '16 А·ч',
    payload: 120,
    stockLabel: 'Под заказ',
    stockTone: 'preorder',
    color: '#37b9ed',
    colorSoft: '#d5f2ff',
    image: '/products/compact-dark.webp',
    imageAlt: 'Чёрный компактный городской электроскутер, вид в три четверти',
    visualVariant: 'compact',
    description: 'Лёгкая модель для коротких заказов, плотных дворов и хранения в небольшой квартире.',
    features: ['Вес 31 кг', 'Складные подножки', 'Компактная база'],
    useCase: 'Короткие маршруты и компактное хранение',
    weight: 31,
    chargeTime: '5–7 часов',
    dimensions: '154 × 66 × 106 см',
    wheelLayout: '2 колеса',
  },
  {
    id: 'gs-city-02',
    category: 'city',
    name: 'Flow Coast 24',
    kicker: 'Комфорт для побережья',
    price: 97900,
    monthly: 8020,
    range: 72,
    speed: 45,
    battery: '24 А·ч',
    payload: 160,
    stockLabel: 'Наличие уточняется',
    stockTone: 'available',
    color: '#9a6df2',
    colorSoft: '#eadfff',
    image: '/products/coast-dark.webp',
    imageAlt: 'Чёрный электроскутер с длинным сиденьем, вид сбоку',
    visualVariant: 'step',
    description: 'Мягкая посадка, увеличенный запас хода и широкие шины для улиц Большого Сочи.',
    features: ['Круиз-контроль', 'USB-C', 'Сигнализация'],
    useCase: 'Комфортные поездки по побережью',
    weight: 64,
    chargeTime: '6–8 часов',
    dimensions: '184 × 72 × 114 см',
    wheelLayout: '2 колеса',
  },
];

export const addons: Addon[] = [
  { id: 'box', name: 'Термокороб 65 л', note: 'Крепление включено', price: 8900 },
  { id: 'lock', name: 'U-lock', note: 'Сталь 14 мм', price: 2900 },
  { id: 'service', name: 'Сервис на 12 месяцев', note: 'Условия уточняются', price: 7900 },
];
