import type { Addon, Product } from './types';

export const products: Product[] = [
  {
    id: 'ml-city-01',
    category: 'city',
    name: 'Volt Street S',
    kicker: 'Городской электроскутер',
    price: 86400,
    oldPrice: 92900,
    monthly: 7080,
    range: 65,
    speed: 45,
    battery: '20 А·ч',
    payload: 150,
    stockLabel: 'Демо: в наличии',
    stockTone: 'available',
    color: '#d8ef47',
    colorSoft: '#edf6bd',
    visualVariant: 'step',
    description: 'Манёвренная городская модель для длинной смены и ежедневных маршрутов по побережью.',
    features: ['Съёмный аккумулятор', 'Гидравлические тормоза', 'Защита от брызг'],
  },
  {
    id: 'ml-cargo-01',
    category: 'cargo',
    name: 'Volt Cargo X',
    kicker: 'Усиленная грузовая рама',
    price: 119900,
    monthly: 9830,
    range: 80,
    speed: 40,
    battery: '32 А·ч',
    payload: 220,
    stockLabel: 'Демо: мало',
    stockTone: 'limited',
    color: '#ff704d',
    colorSoft: '#ffd5cb',
    visualVariant: 'cargo',
    description: 'Усиленная конструкция для двух термокоробов и маршрутов с высокой загрузкой.',
    features: ['Задняя грузовая платформа', 'Двойная подножка', 'Усиленная подвеска'],
  },
  {
    id: 'ml-compact-01',
    category: 'compact',
    name: 'Zip Mini 14',
    kicker: 'Компактный формат',
    price: 74900,
    monthly: 6140,
    range: 48,
    speed: 35,
    battery: '16 А·ч',
    payload: 120,
    stockLabel: 'Демо: предзаказ',
    stockTone: 'preorder',
    color: '#7ed7ee',
    colorSoft: '#d4f3fa',
    visualVariant: 'compact',
    description: 'Лёгкая модель для коротких заказов, плотных дворов и хранения в небольшой квартире.',
    features: ['Вес 31 кг', 'Складные подножки', 'Компактная база'],
  },
  {
    id: 'ml-city-02',
    category: 'city',
    name: 'Flow Coast 24',
    kicker: 'Комфорт для побережья',
    price: 97900,
    monthly: 8020,
    range: 72,
    speed: 45,
    battery: '24 А·ч',
    payload: 160,
    stockLabel: 'Демо: в наличии',
    stockTone: 'available',
    color: '#9f91f6',
    colorSoft: '#e3defd',
    visualVariant: 'step',
    description: 'Мягкая посадка, увеличенный запас хода и широкие шины для улиц Большого Сочи.',
    features: ['Круиз-контроль', 'USB-C', 'Сигнализация'],
  },
];

export const addons: Addon[] = [
  { id: 'box', name: 'Термокороб 65 л', note: 'Крепление включено', price: 8900 },
  { id: 'lock', name: 'U-lock', note: 'Сталь 14 мм', price: 2900 },
  { id: 'service', name: 'Сервис на 12 месяцев', note: 'Демо-условия', price: 7900 },
];

